### ISSUE TITLE
튜토리얼의 일부 링크가 깨집니다

### ISSUE THREAD

**Issue by constmoon** [pofoldev/pofol-dev-workshop#2]
안녕하세요? 사이트를 차례대로 읽어보던 참에 이슈를 발견하여 올립니다.
https://pofol.dev/tutorials 의 일부 페이지 링크가 깨집니다. 연결된 페이지가 없다고 나와요.
튜토리얼의 **더 배울 것** 파트에서

  - Git을 사용한 코드 관리와 협력
  - 디자인 시스템

이 두 파트의 링크가 깨집니다.
[문서 저장소](https://github.com/pofoldev/pofol-dev-workshop/tree/master/tutorial)를 보면 해당하는 문서가 없는 것 같은데, 아직 생성되지 않은 문서라 일어난 문제인가요? 
개인적으로 알고 싶었던 부분이라 궁금합니다.

**Comment by lexifdev** [comment]
아직 튜토리얼은 작성중인 단계라 빠져있는 파일이 종종 있습니다.
우선 알려주신 김에 링크 라도 깨지지 말라고 작업중인 파일을 올려두었어요.
